### ISSUE TITLE
Visual hints for each metric

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/SegmentationEvaluationConsole#11]
Feature request:

The metrics include nice tooltip descriptions if you click on them.  It might be nice to add "higher is better" or "lower is better" to each (when applicable).  Bonus points: Some sort of grouping or color-coding might be another way to convey that information.

Furthermore, when comparing two sets of metrics (via the "Compare" button), it would be nice to highlight the "winning" score in each row, just to get a quick visual overview.

**Comment by ghost** [comment]
Deployed! Definitely let me know if the icons aren't quite right--I was wondering if the certificate icon might read as a tiny sun to some people.

**Comment by stuarteberg** [comment]
Nice, thanks!  Looks good.  Now it's easier to quickly load and compare two experiments.  The little ☀️ icon makes it easy to see at a glance if one segmentation dominates the comparisons.  I don't think the exact icon choice matters too much.
